export const ACTION_LABELS: Record<string, string> = {
  login: 'Inicio de sesión',
  login_failed: 'Login fallido',
  logout: 'Cierre de sesión',
  'stay.checkin': 'Check-in',
  'stay.checkout': 'Check-out',
  'stay.payment': 'Pago registrado',
  'stay.payment_cancelled': 'Pago anulado',
  'stay.minibar_cancelled': 'Consumo de minibar anulado',
  'stay.minibar': 'Venta de productos (estadía)',
  'minibar_sale.created': 'Venta de productos creada',
  'minibar_sale.paid': 'Venta de productos pagada',
  'minibar_sale.cancelled': 'Venta de productos cancelada',
  'stay.service': 'Servicio agregado',
  'stay.transfer': 'Transferencia de habitación',
  'stay.extended': 'Estadía extendida',
  'stay.void_requested': 'Anulación de estadía solicitada',
  'stay.void_approved': 'Anulación de estadía aprobada',
  'stay.void_rejected': 'Anulación de estadía rechazada',
  'reservation.created': 'Reserva creada',
  'reservation.cancelled': 'Reserva cancelada',
  'reservation.payment_cancelled': 'Pago de reserva anulado',
  'reservation.updated': 'Reserva actualizada',
  'reservation.group_created': 'Reserva grupal creada',
  'reservation.checkin': 'Check-in desde reserva',
  room_created: 'Habitación creada',
  room_updated: 'Habitación actualizada',
  room_deactivated: 'Habitación desactivada',
  room_status_changed: 'Cambio de estado',
  'room.status_changed': 'Cambio de estado',
  'room.cleaning': 'Limpieza de habitación',
  'room.maintenance': 'Mantenimiento de habitación',
  'inventory.restock': 'Reposición de inventario',
  'inventory.adjust': 'Ajuste de inventario',
}

export const PAYLOAD_LABELS: Record<string, string> = {
  stay_id: 'ID Estadía',
  guest_name: 'Huésped',
  rooms: 'Habitaciones',
  total_amount: 'Total',
  total: 'Total',
  amount: 'Monto',
  method: 'Método de pago',
  type: 'Tipo',
  reason: 'Motivo',
  payment_id: 'ID Pago',
  from_room_id: 'Desde (ID hab.)',
  to_room_id: 'Hacia (ID hab.)',
  room_id: 'ID Habitación',
  room_number: 'Habitación',
  old_status: 'Estado anterior',
  new_status: 'Nuevo estado',
  new_check_out: 'Nueva salida',
  new_nights: 'Nuevas noches',
  service_name: 'Servicio',
  quantity: 'Cantidad',
  ip: 'Dirección IP',
  email: 'Email',
  product_name: 'Producto',
  sale_number: 'N° venta',
  items_count: 'Productos',
  admin_notes: 'Observaciones admin',
  void_request_id: 'ID solicitud anulación',
  payment_method: 'Método de pago',
  was_paid: 'Estaba pagada',
  items: 'Detalle',
  guest_id: 'ID Huésped',
  company_name: 'Empresa',
  reservation_id: 'ID Reserva',
  room_count: 'Habitaciones',
  by_name: 'Realizado por',
  start_date: 'Llegada',
  end_date: 'Salida',
  agreed_price: 'Precio acordado',
  deposit_amount: 'Abono',
  nights: 'Noches',
  status: 'Estado',
  billing_mode: 'Facturación',
  group_id: 'Grupo',
}

export const METHOD_LABELS: Record<string, string> = {
  cash: 'Efectivo',
  transfer: 'Transferencia',
  card: 'Tarjeta',
  credito: 'Crédito',
}

export const STATUS_LABELS: Record<string, string> = {
  available: 'Disponible',
  occupied: 'Ocupada',
  reserved: 'Reservada',
  cleaning: 'Limpieza',
  maintenance: 'Mantenimiento',
  blocked: 'Bloqueada',
  deposit: 'Depósito',
  partial: 'Parcial',
  final: 'Final',
}

export const ROLE_LABELS: Record<string, string> = {
  superadmin: 'Super administrador',
  admin: 'Administrador',
  receptionist: 'Recepcionista',
  housekeeping: 'Aseo',
  maintenance: 'Mantenimiento',
}
